version: "3.7"
services:
    frontend:
        build:
            context: frontend/docker/nginx
        ports:
            - "8080:80"
        volumes:
        - ./frontend:/app
    api:
        build:
            context: api/docker/nginx
        ports:
            - "8081:80"
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
    api-php-fpm:
        build:
            context: api/docker/php-fpm
        volumes:
            - ./api:/app