version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker/nginx
        ports:
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
        depends_on:
          - frontend
          - api
          - mailer
    frontend:
        build:
            context: frontend/docker/nginx
        volumes:
        - ./frontend:/app
    api:
        build:
            context: api/docker/nginx
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
    api-php-fpm:
        build:
            context: api/docker
            dockerfile: php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost:8080
        volumes:
            - ./api:/app
    api-php-cli:
        build:
            context: api/docker
            dockerfile: php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USER: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app.test
            FRONTEND_URL: http://localhost:8080
        volumes:
            - ./api:/app
    api-postgres:
        image: postgres:12.2-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"
    mailer:
        image: mailhog/mailhog
volumes:
    api-postgres:
