version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker/nginx
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
          - frontend
          - api
    frontend:
        build:
            context: frontend/docker/nginx
        volumes:
        - ./frontend:/app
    api:
        build:
            context: api/docker/nginx
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
    api-php-fpm:
        build:
            context: api/docker
            dockerfile: php-fpm/Dockerfile
        volumes:
            - ./api:/app
    api-php-cli:
        build:
            context: api/docker
            dockerfile: php-cli/Dockerfile
        volumes:
            - ./api:/app